services:
  - type: web
    name: telegram-leech-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn health:app & python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
